name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  TERRAFORM_VERSION: 0.13.0
  IMAGE_NAME: azure-network-module

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: build
      run: bundle exec rake
      if: type = pull_request
    - name: full
      if: type = push AND branch = master
      run: |
        docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t ${IMAGE_NAME} .
        docker run ${IMAGE_NAME} rake full  
